name: FrameDupe
version: '${project.version}'
description: '${project.description}'
website: '${project.url}'
main: me.MrRafter.framedupe.FrameDupe
api-version: 1.13
authors: [ xGinko, MrRafter ]
folia-supported: true

commands:
  framedupe:
    permission: framedupe.cmd.*
    description: Admin commands
    usage: /framedupe [ reload, version ]
    aliases:
      - fd

permissions:
  framedupe.bypass.cooldown:
    description: Cooldown bypass if enabled
  framedupe.bypass.chance:
    description: Random chance bypass
  framedupe.bypass.blacklist:
    description: Item blacklist bypass
  framedupe.bypass.whitelist:
    description: Item whitelist bypass
  framedupe.cmd.*:
    description: Command permissions
    children:
      framedupe.cmd.reload: true
      framedupe.cmd.version: true
  framedupe.cmd.reload:
    description: Reload the plugin
  framedupe.cmd.version:
    description: Show the plugin version